@host = localhost:8080

// Register User
POST http://{{host}}/user/register HTTP/1.1
content-type: application/json
    

{
    "name": "Max",
    "username": "Max",
    "email": "Max@gmail.com",
    "password": "Max",
    "role": "User"
}

###

